export const GET_ADDRESS_DATA_REQUEST = 'GET_ADDRESS_DATA_REQUEST';
export const GET_ADDRESS_DATA_SUCCESS = 'GET_ADDRESS_DATA_SUCCESS';
export const GET_ADDRESS_DATA_FAILED = 'GET_ADDRESS_DATA_FAILED';
